baseurl      = "http://ruby2elixir.github.io/"
languageCode = "en-us"
title        = "Ruby 2 Elixir Blog"
theme        = "cactus"
canonifyurls = true
uglyurls     = true




[permalinks]
  post = "posts/:year/:month-:day-:slug.html"

[params]
  description     = "Community-driven initiative to switch from Ruby to Elixir"
  bio             = "Why the future of web development is changing once again..."
  name            = "RUBY 2 ELIXIR"
  disqusShortname = "ruby2elixir"
  googleAnalytics = "UA-71514130-1"

[params.authors]
  [params.authors.mindreframer]
    name             = "Roman Heinrich"
    gravatar_id      = 'b540757705fa11df3313d5396a3649d9'
    facebook         = "https://www.facebook.com/derekperkins"
    github           = "https://github.com/mindreframer/"
    github_username  = 'mindreframer'
    twitter          = "https://twitter.com/mindreframer"
    twitter_username = 'mindreframer'
    gplus            = "https://plus.google.com/+mindreframer"
    bio              = "Hopeless practitioner in search for the perfect prog language..."


[taxonomies]
  category = "categories"
  tag      = "tags"
